baseURL = "https://ahmadtheswe.github.io/"
languageCode = "en"
title = "ahmadtheswe blog"
theme = "LoveIt"
languageName = "English"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[params]
  title = "ahmadtheswe blog"
  description = "A pragmatic script painter"
  defaultTheme = "auto"

  [params.home.profile]
    subtitle = "Welcome to ahmadtheswe blog, a place where I share my thoughts and ideas."
    avatarURL = "https://github.com/ahmadtheswe.png"

  [params.author]
    name = "ahmad"
    email = "ahmadtheswe@gmail.com"
    link = ""

  [params.header.title]
    logo = "https://github.com/ahmadtheswe.png"
    name = "ahmadtheswe blog"
    pre = ""
    post = ""
    typeit = false

  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    author = true
    since = 2025
    icp = ""
    license= "ahmadtheswe"

  [params.social]
    GitHub = "ahmadtheswe"
    Linkedin = "ahmad-mujahid-abdurrahman"
    X = "ahmadtheswe"
    Instagram = "ahmadtheswe"
    Threads = "ahmadtheswe"

  [params.page.share]
    enable = true
    X = true
    Threads = true
    Facebook = true
    Linkedin = true
    Whatsapp = true
    Telegram = true
    Diaspora = false
    Weibo = false
    Line = false

  [params.search]
    enable = false
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "privacy-policy"
    pre = ""
    post = ""
    name = "Privacy Policy"
    url = "/privacy-policy/"
    title = ""

[markup]
  [markup.highlight]
    noClasses = false